# Generated by Django 4.2.4 on 2023-10-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("grade", models.IntegerField()),
                ("age", models.IntegerField()),
                ("home_address", models.CharField(max_length=55)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "M"), ("Female", "F")], max_length=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userRank",
            fields=[
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("deposit", models.IntegerField(default=1000000)),
                ("earning_rate", models.FloatField(default=0)),
            ],
        ),
    ]
