# Generated by Django 4.2.4 on 2023-11-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ip",
            fields=[("ipId", models.AutoField(primary_key=True, serialize=False)),],
            options={"db_table": "ip",},
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                ("sessionId", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={"db_table": "sessions",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("grade", models.IntegerField()),
                ("age", models.IntegerField()),
                ("home_address", models.CharField(max_length=55)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "M"), ("Female", "F")], max_length=6
                    ),
                ),
            ],
            options={"db_table": "student",},
        ),
        migrations.CreateModel(
            name="userRank",
            fields=[
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("deposit", models.IntegerField(default=1000000)),
                ("earning_rate", models.FloatField(default=0)),
            ],
            options={"db_table": "userrank",},
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                ("affiliationId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ip",
                    models.ForeignKey(
                        db_column="ipId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.ip",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_column="sessionId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.sessions",
                    ),
                ),
            ],
            options={"db_table": "affiliation",},
        ),
    ]
