# Generated by Django 4.2.4 on 2023-10-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="student", options={"managed": False},),
        migrations.AlterModelOptions(name="userrank", options={"managed": False},),
    ]
