# Generated by Django 4.2.4 on 2023-10-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0002_alter_student_options_alter_userrank_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="student", options={"managed": True},),
        migrations.AlterModelTable(name="userrank", table="userank",),
    ]
