# Generated by Django 4.2.4 on 2023-10-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_alter_student_options_alter_userrank_table"),
    ]

    operations = [
        migrations.AlterModelOptions(name="student", options={"managed": False},),
    ]
