# Generated by Django 4.2.4 on 2023-10-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelTable(name="student", table="student",),
    ]
