# Generated by Django 4.2.4 on 2023-10-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0005_alter_student_table"),
    ]

    operations = [
        migrations.AlterModelOptions(name="student", options={},),
    ]
