# Generated by Django 4.2.4 on 2023-10-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0006_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="student", options={"managed": False},),
    ]
