# Generated by Django 4.2.4 on 2023-11-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0007_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelTable(name="userrank", table="userrank",),
    ]
